name: MyUniverse
options:
  bundleIdPrefix: com.fangyu
targets:
  MyUniverse:
    type: bundle
    platform: macOS
    deploymentTarget: "11.0"
    sources:
      - Sources
    info:
      path: Info.plist
      properties:
        NSPrincipalClass: "$(PRODUCT_MODULE_NAME).MyUniverseView"
    settings:
      WRAPPER_EXTENSION: saver
      SWIFT_VERSION: "5.0"
      CODE_SIGN_IDENTITY: "-"
